apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: aws code deploy actions
inputs:
  application-name: 
    description: 'application name'
    required: true
  description:  
    description: 'description'
    required: true
  deployment-group-name:
    description: 'deployment group name'
    required: true
  deployment-config-name: 
    description: 'deployment configuration name'
    required: true
  update-outdated-instances-only:
    description: 'Update outdated instances only'
    required: false
    default: 'false'
  ignore-application-stop-failures: 
    description: 'Ignore application stop failures'
    required: false
    default: 'false'
  file-exists-behavior: 
    description: 'File exists behavior'
    required: false
  revision-type: 
    description: 'Type of the revision (S3 or GitHub or AppSpec)'
    required: true
  s3-bucket:
    description: 'S3 bucket name'
    required: false
  s3-key:
    description: 'S3 key for the deployment package'
    required: false
  s3-bundle-type:
    description: 'S3 bundle type'
    required: false
  s3-artifact-version:
    description: 'S3 artifact version'
    required: false
  github-repository:
    description: 'GitHub repository name'
    required: false
  github-commit-id:  
    description: 'GitHub commit id'
    required: false
  appspec-content:
    description: 'Content of the AppSpec file'
    required: false
  appspec-content-sha:
    description: 'SHA of the AppSpec file'
    required: false
  string-content:
    description: 'Content of the string'
    required: false
  string-content-sha:
    description: 'SHA of the string'
    required: false
  auto-rollback-enabled: 
    description: 'Enable auto rollback'
    required: false
    default: 'false'
  auto-rollback-events:
    description: 'Auto rollback events'
    required: false
    default: '[]'
  override-alarm-names:
    description: 'Alarm configuration'
    required: false
    default: '[]'
  override-alarm-enabled:
    description: 'Alarm configuration enabled'
    required: false
    default: 'false'
  target-auto-scaling-groups:
    description: 'Target auto scaling groups'
    required: false
    default: '[]'
  target-instance-tag-filters:
    description: 'Target instance tag filters'
    required: false
    default: '[]'
  target-instance-tag-set:
    description: 'Target instance tag set'
    required: false
    default: '[]'
    
      
runs:
  using: composite
  steps:
    - id: invoke-aws-code-deploy-job
      name: invoke-aws-code-codedeploy-job
      uses: docker://public.ecr.aws/l7o7z1g8/actions/aws-codedeploy-invoke-actions:main-ea51b9ff8ebfd12dda01c2378b1bfbd3a4470035
      shell: sh
      env:
        CONFIG_JSON: '{"metaInfo":{"action":"AWS_CODEDEPLOY_ACTIONS","applicationName":"${{ inputs.application-name }}","description":"${{ inputs.description }}","deploymentGroupName":"${{ inputs.deployment-group-name }}","deploymentConfigName":"${{ inputs.deployment-config-name }}","updateOutdatedInstancesOnly":${{ inputs.update-outdated-instances-only }},"fileExistsBehavior":"${{ inputs.file-exists-behavior }}","IgnoreApplicationStopFailures":${{ inputs.ignore-application-stop-failures }},"revision":{"revisionType":"${{ inputs.revision-type }}","s3location":{"bucket":"${{ inputs.s3-bucket }}","key":"${{ inputs.s3-key }}","bundleType":"${{ inputs.s3-bundle-type }}"},"gitHubLocation":{"repository":"${{ inputs.github-repository }}","commitId":"${{ inputs.github-commit-id }}"},"appSpecContent":{"content":"${{ inputs.appspec-content }}","sha256":"${{ inputs.appspec-content-sha }}"},"string":{"content":"${{ inputs.string-content }}","sha256":"${{ inputs.string-content-sha }}"}},"autoRollbackConfiguration":{"enabled":"${{ inputs.auto-rollback-enabled }}","events":${{ inputs.auto-rollback-events }}},"overrideAlarmConfiguration":{"enabled":${{ inputs.override-alarm-enabled }},"alarms":${{ inputs.override-alarm-names }}},"targetInstances":{"autoScalingGroups":${{ inputs.target-auto-scaling-groups }},"tagFilters":${{ inputs.target-instance-tag-filters }},"ec2TagSet":{"ec2TagSetList":${{ inputs.target-instance-tag-set }}}}}}'
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{ step.internal.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: |
        set -x
        cd /app
        ./aws_codedeploy_actions_app invoke -i $CONFIG_JSON